# Use Java base image
FROM openjdk:17-jdk-slim

# Create working dir
WORKDIR /app

# Copy the jar to container
COPY target/*.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the jar
ENTRYPOINT ["java", "-jar", "app.jar"]
